# Generated by Django 5.1.3 on 2024-11-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_rename_text_review_comment_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='directors', to='movie_app.movie'),
        ),
    ]
