# Generated by Django 5.1.3 on 2024-11-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_director_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='movies_count',
            field=models.IntegerField(default=0),
        ),
    ]
