# Generated by Django 5.1.3 on 2024-11-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_director_movies_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movies_count',
        ),
    ]
